/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author RONALD
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        LocalDate now = LocalDate.now();
        int año = now.getYear();
        int dia = now.getDayOfMonth();
        int mes = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," Septiembre"
            ,"Octubre","Noviembre","Diciemrbre"};
        lblFecha.setText("Fecha: "+dia+" de "+meses[mes-1]+" de "+año);
        Perfiles perfil = new Perfiles();
        perfil.setSize(560,380);
        perfil.setLocation(0,0);
        Contenido.removeAll();
        Contenido.add(perfil, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }
    public void MostrarPanel(JPanel panel){
        panel.setSize(560,380);
        panel.setLocation(0,0);
        Contenido.removeAll();
        Contenido.add(panel, BorderLayout.CENTER);
        Contenido.revalidate();
        Contenido.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        FondoMenu = new javax.swing.JPanel();
        btnAlumno = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        btnDocente = new javax.swing.JPanel();
        lblDocente = new javax.swing.JLabel();
        btnCursos = new javax.swing.JPanel();
        lblCursos = new javax.swing.JLabel();
        btnMatriculas = new javax.swing.JPanel();
        lblMatriculas = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JPanel();
        lblPerfil = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoMenu.setBackground(new java.awt.Color(30, 136, 26));
        FondoMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlumno.setBackground(new java.awt.Color(30, 136, 26));
        btnAlumno.setPreferredSize(new java.awt.Dimension(70, 40));

        lblAlumno.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(255, 255, 255));
        lblAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlumno.setText("ALUMNO");
        lblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAlumnoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAlumnoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAlumnoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnAlumnoLayout = new javax.swing.GroupLayout(btnAlumno);
        btnAlumno.setLayout(btnAlumnoLayout);
        btnAlumnoLayout.setHorizontalGroup(
            btnAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnAlumnoLayout.setVerticalGroup(
            btnAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        FondoMenu.add(btnAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 110, -1));

        btnDocente.setBackground(new java.awt.Color(30, 136, 26));
        btnDocente.setPreferredSize(new java.awt.Dimension(70, 40));

        lblDocente.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblDocente.setForeground(new java.awt.Color(255, 255, 255));
        lblDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDocente.setText("DOCENTE");
        lblDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDocenteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDocenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDocenteMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnDocenteLayout = new javax.swing.GroupLayout(btnDocente);
        btnDocente.setLayout(btnDocenteLayout);
        btnDocenteLayout.setHorizontalGroup(
            btnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDocenteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnDocenteLayout.setVerticalGroup(
            btnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnDocenteLayout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(lblDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FondoMenu.add(btnDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 110, -1));

        btnCursos.setBackground(new java.awt.Color(30, 136, 26));
        btnCursos.setPreferredSize(new java.awt.Dimension(70, 40));

        lblCursos.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblCursos.setForeground(new java.awt.Color(255, 255, 255));
        lblCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCursos.setText("CURSOS");
        lblCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCursosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCursosLayout = new javax.swing.GroupLayout(btnCursos);
        btnCursos.setLayout(btnCursosLayout);
        btnCursosLayout.setHorizontalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnCursosLayout.setVerticalGroup(
            btnCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        FondoMenu.add(btnCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 110, -1));

        btnMatriculas.setBackground(new java.awt.Color(30, 136, 26));
        btnMatriculas.setPreferredSize(new java.awt.Dimension(70, 40));

        lblMatriculas.setBackground(new java.awt.Color(255, 255, 255));
        lblMatriculas.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        lblMatriculas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMatriculas.setText("MATRICULAS");
        lblMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMatriculasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMatriculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMatriculasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMatriculasLayout = new javax.swing.GroupLayout(btnMatriculas);
        btnMatriculas.setLayout(btnMatriculasLayout);
        btnMatriculasLayout.setHorizontalGroup(
            btnMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnMatriculasLayout.setVerticalGroup(
            btnMatriculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMatriculas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        FondoMenu.add(btnMatriculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 110, -1));

        btnPerfil.setBackground(new java.awt.Color(255, 255, 255));
        btnPerfil.setPreferredSize(new java.awt.Dimension(70, 40));

        lblPerfil.setBackground(new java.awt.Color(255, 255, 255));
        lblPerfil.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        lblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPerfil.setText("PERFIL");
        lblPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPerfilMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnPerfilLayout = new javax.swing.GroupLayout(btnPerfil);
        btnPerfil.setLayout(btnPerfilLayout);
        btnPerfilLayout.setHorizontalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnPerfilLayout.setVerticalGroup(
            btnPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPerfil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        FondoMenu.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 110, -1));

        Fondo.add(FondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 440));

        Header.setBackground(new java.awt.Color(30, 136, 26));

        lblFecha.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha: 12 de Septiembre de 2022");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        Fondo.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 560, 60));

        Contenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        Fondo.add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 560, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlumnoMouseClicked

        btnAlumno.setBackground(Color.white);
        lblAlumno.setForeground(Color.black);
        btnCursos.setBackground(new Color(30,136,26));
        lblCursos.setForeground(Color.white);
        btnDocente.setBackground(new Color(30,136,26));
        lblDocente.setForeground(Color.white);
        btnPerfil.setBackground(new Color(30,136,26));
        lblPerfil.setForeground(Color.white);
        btnMatriculas.setBackground(new Color(30,136,26));
        lblMatriculas.setForeground(Color.white);
        Alumno PanelAlumno = new Alumno();
        MostrarPanel(PanelAlumno);

    }//GEN-LAST:event_lblAlumnoMouseClicked

    private void lblDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocenteMouseClicked

        btnAlumno.setBackground(new Color(30,136,26));
        lblAlumno.setForeground(Color.white);
        btnCursos.setBackground(new Color(30,136,26));
        lblCursos.setForeground(Color.white);
        btnDocente.setBackground(Color.white);
        lblDocente.setForeground(Color.black);
        btnPerfil.setBackground(new Color(30,136,26));
        lblPerfil.setForeground(Color.white);
        btnMatriculas.setBackground(new Color(30,136,26));
        lblMatriculas.setForeground(Color.white);
        Docente PanelDocente = new Docente();
        MostrarPanel(PanelDocente);
    }//GEN-LAST:event_lblDocenteMouseClicked

    private void lblCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosMouseClicked

        btnAlumno.setBackground(new Color(30,136,26));
        lblAlumno.setForeground(Color.white);
        btnCursos.setBackground(Color.white);
        lblCursos.setForeground(Color.black);
        btnDocente.setBackground(new Color(30,136,26));
        lblDocente.setForeground(Color.white);
        btnPerfil.setBackground(new Color(30,136,26));
        lblPerfil.setForeground(Color.white);
        btnMatriculas.setBackground(new Color(30,136,26));
        lblMatriculas.setForeground(Color.white);
        Cursos PanelCursos = new Cursos();
        MostrarPanel(PanelCursos);
    }//GEN-LAST:event_lblCursosMouseClicked

    private void lblMatriculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMatriculasMouseClicked

        btnAlumno.setBackground(new Color(30,136,26));
        lblAlumno.setForeground(Color.white);
        btnCursos.setBackground(new Color(30,136,26));
        lblCursos.setForeground(Color.white);
        btnDocente.setBackground(new Color(30,136,26));
        lblDocente.setForeground(Color.white);
        btnPerfil.setBackground(new Color(30,136,26));
        lblPerfil.setForeground(Color.white);
        btnMatriculas.setBackground(Color.white);
        lblMatriculas.setForeground(Color.black);
        Matriculas PanelMatriculas = new Matriculas();
        MostrarPanel(PanelMatriculas);
    }//GEN-LAST:event_lblMatriculasMouseClicked

    private void lblAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlumnoMouseEntered
        btnAlumno.setBackground(Color.white);
        lblAlumno.setForeground(Color.black);
    }//GEN-LAST:event_lblAlumnoMouseEntered

    private void lblAlumnoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAlumnoMouseExited
        if (btnPerfil.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnCursos.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() ||
                btnDocente.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnMatriculas.getBackground().getRGB()!= FondoMenu.getBackground().getRGB()) {
            btnAlumno.setBackground(new Color(30,136,26));
            lblAlumno.setForeground(Color.white);         
        }
    }//GEN-LAST:event_lblAlumnoMouseExited

    private void lblPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseClicked
        // TODO add your handling code here:
        btnAlumno.setBackground(new Color(30,136,26));
        lblAlumno.setForeground(Color.white);
        btnCursos.setBackground(new Color(30,136,26));
        lblCursos.setForeground(Color.white);
        btnDocente.setBackground(new Color(30,136,26));
        lblDocente.setForeground(Color.white);
        btnPerfil.setBackground(Color.white);
        lblPerfil.setForeground(Color.black);
        btnMatriculas.setBackground(new Color(30,136,26));
        lblMatriculas.setForeground(Color.white);
        Perfiles PanelPerfil = new Perfiles();
        MostrarPanel(PanelPerfil);
    }//GEN-LAST:event_lblPerfilMouseClicked

    private void lblPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseEntered
        // TODO add your handling code here:
        btnPerfil.setBackground(Color.white);
        lblPerfil.setForeground(Color.black);
    }//GEN-LAST:event_lblPerfilMouseEntered

    private void lblPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPerfilMouseExited
        // TODO add your handling code here:
        if (btnAlumno.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnCursos.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() ||
                btnDocente.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnMatriculas.getBackground().getRGB()!= FondoMenu.getBackground().getRGB()) {
            btnPerfil.setBackground(new Color(30,136,26));
            lblPerfil.setForeground(Color.white);         
        }
    }//GEN-LAST:event_lblPerfilMouseExited

    private void lblDocenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocenteMouseEntered
        // TODO add your handling code here:
        btnDocente.setBackground(Color.white);
        lblDocente.setForeground(Color.black);
    }//GEN-LAST:event_lblDocenteMouseEntered

    private void lblDocenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocenteMouseExited
        // TODO add your handling code here:
        if (btnAlumno.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnCursos.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() ||
                btnPerfil.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnMatriculas.getBackground().getRGB()!= FondoMenu.getBackground().getRGB()) {
            btnDocente.setBackground(new Color(30,136,26));
            lblDocente.setForeground(Color.white);         
        }
    }//GEN-LAST:event_lblDocenteMouseExited

    private void lblCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosMouseEntered
        // TODO add your handling code here:
        btnCursos.setBackground(Color.white);
        lblCursos.setForeground(Color.black);
    }//GEN-LAST:event_lblCursosMouseEntered

    private void lblCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosMouseExited
        // TODO add your handling code here:
        if (btnAlumno.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnPerfil.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() ||
                btnDocente.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnMatriculas.getBackground().getRGB()!= FondoMenu.getBackground().getRGB()) {
            btnCursos.setBackground(new Color(30,136,26));
            lblCursos.setForeground(Color.white);         
        }
    }//GEN-LAST:event_lblCursosMouseExited

    private void lblMatriculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMatriculasMouseEntered
        // TODO add your handling code here:
        btnMatriculas.setBackground(Color.white);
        lblMatriculas.setForeground(Color.black);
    }//GEN-LAST:event_lblMatriculasMouseEntered

    private void lblMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMatriculasMouseExited
        // TODO add your handling code here:
        if (btnAlumno.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnCursos.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() ||
                btnDocente.getBackground().getRGB()!= FondoMenu.getBackground().getRGB() || btnPerfil.getBackground().getRGB()!= FondoMenu.getBackground().getRGB()) {
            btnMatriculas.setBackground(new Color(30,136,26));
            lblMatriculas.setForeground(Color.white);         
        }
    }//GEN-LAST:event_lblMatriculasMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel FondoMenu;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel btnAlumno;
    private javax.swing.JPanel btnCursos;
    private javax.swing.JPanel btnDocente;
    private javax.swing.JPanel btnMatriculas;
    private javax.swing.JPanel btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblCursos;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMatriculas;
    private javax.swing.JLabel lblPerfil;
    // End of variables declaration//GEN-END:variables
}
